### ISSUE TITLE
Create "Question queue" or "Laboratory" page

### ISSUE THREAD

**Issue by liaprins** [liaprins/curiositycoloredglasses.com#119]
It should be second in the menu right after Hello, followed by Library, then Archive.

- [x] Come up with a strategy for how to automatically position the glasses icons with code
- I have created and hooked up qq-position.js to start exploring. I want to try to use JS's ability to count through for-loops and assign numbers in an array. It can be used with math in the script to assign distances for position to its CSS inline, like the positioning of slides in slideshows. May need to reference my JS book's counting section to brush up. I am currently in the process of testing the script and variables with a test id I added temporarily to questionqueue.php template. Next step is to start testing the counting and then math applied to it and then assign to CSS, just experimentally. Then keep experimenting to get to more of a specific strategy/plan for how to use this functionality to position.

- [x] Plan how to account for growable heights in parallax 
- **Idea:** `pairRowCount` times the number of pixels I assign to each vertical position. Then pass this to a `data-XXX` attribute (e.g. `data-height`) on any/all of the .qqpiece `<span>`s (or similar) and collect it again via `document.querySelectorAll('.qqpiece')[0].getAttribute('data-height')` (warning: pseudo-code!) in the qq-parallax.js script to use.

**Binoculars CSS mask**
- [x] Design geometry for the binoculars icon.
- [x] Figure out CSS for the binoculars icon.
- [x] Implement CSS-made binocular mask into the for loop instead of SVG so that I don't have to worry about glasses overlapping each other.
- [x] Finesse zooming so that only one BG img with both lens BGs is needed (will need to create new BG imgs to test with).
- https://stackoverflow.com/questions/20093822/css-background-image-to-fit-height-width-should-auto-scale-in-proportion
- https://www.w3schools.com/cssref/css3_pr_background-size.asp
- [x] Change DOM navigation within qq.js accordingly.
- [x] Adjust HTML and JS, etc so that content is tied to binocular position despite parallax's position .(may need to go into all the `qq` JS files, at least qq.js and also questionqueue.php)
- [x] Fix parallax bug!

**Perfect positioning**
- [x] Set up `qq-position.js` to position large glasses separate from medium, separate from small, *but still use the current basic positioning scheme concept for each independently!*
- [x] Figure out how to deal with extra binocular pair (small, eye-black)...I think the algorithm isn't accounting for remainder after dividing by the number provided...)
- [x] Fix remainder binoculars beyond "perfect grids" using pseudocode in notebook.
- [x] Create boxes to stand-in for margin parameters.
- [x] Finesse maximum allowed margin variables and grids for each binocular size until I like the pattern.
- [x] Get binoc positioning to work at all screen sizes.
- [x] Adjust L, M, S binoc (and boxes) sizes (via CSS media query) for all screen sizes (mimic breakpoints established in JS for positioning; just one at 1225 for px; all before that at vw).
- [x] Make notebook checkbox list documenting the permutations of remainders to test.
- [x] Test all permutations of remainders on boxes, according to notebook checkbox list.
- [x] Create plan for how to adjust margin randomization sizes in questionqueue.php to repond to 1225 breakpoint, and use vw before it and px after: consider using JS somehow.
- [x] Transfer positioning screen size box code in JS to binocs, too (remember to add `.parentNode` immediately after `[array number/identifier]`). 
- [x] Implement pseudocode from notebook for responsive randomized margins (test via Inspector hover state). _*Update:* This will not work because JS can't properly pass PHP variables. See my attempts in the included folder `qq-binocular-responsive-randomized-margin-attempt`. See lines *93-99* in `questionqueue.php`, and lines *7-24* in `qq-position.js` (uncomment)._
[qq-binocular-responsive-randomized-margin-attempt.zip](https://github.com/liaprins/curiositycoloredglasses.com/files/2488118/qq-binocular-responsive-randomized-margin-attempt.zip)
- [x] Consider having different available margin widths for each binocular size (would need to establish each in questionqueue.php and call within each `if (qqScreenWidth < 1225) {` if-statement in qq-position.php (test via Inspector hover state). _*Update:* This will not work because JS can't properly pass PHP variables._

**Panel**
- [x] Get panel to allow images to be re-ordered via dragging again.
- Dragging to re-order works great in liaprins.com's localhost panel; so I tried replacing the `kirby` and `panel` folders in curiositycoloredglasses.com's localhost with the ones from liaprins.com's localhost. (Those are the two folders they tell you to replace when there are new Kirby versions available.) However, this did not work.
- https://forum.getkirby.com/t/saving-an-image-reset-order-in-the-panel/645
- May need to ask a question in the panel.
- [x] Update online version's `kirby` and `panel` folders to latest version, and also replace their `library.yml` and `gallery.yml` files. (FIRST DOWNLOAD THESE TO LOCAL COMPUTER AS A BACKUP!)

**Page content**
- [x] Fix font of page description.
- [x] Fix position of page title and description at all sizes.
- [x] Write final page description.

**Perfect parallax**
- [x] Perfect calculation for height of parallax layer. This will probably mean accounting for the small glasses' parallax scroll co-effiecient (assigned within qq-parallax.js) within lines 259 and 271 of qq-position.js somehow... Also may need to account for height of window... See also pull request #144 commentary.
- [x] ... at all screen sizes.
- [x] add parallax scroll rate to page title + page paragraph (+ menu?) *NOTE: I could not get this to apply, so am just leaving these with the regular scroll rate.*

**Footer**
- [x] Fix footer positioning so it stays at bottom and doesn't overlap any binoculars (see plan in notebook).
- [x] ... at all screen sizes: figure out why lines 253 and 259 of qq-position.js aren't working!

**Menu**
- [x] Get menu to stay at top.
- [x] Finesse individual binoculars from overlapping menu *and title and intro* at start, at 1225+.
- [x] ... at all screen sizes.
- [x] Clean up all comments.

**Other**
- [x] Fix "Subscribe button in footer at all sizes
- [x] Fix one binoc pair that now overlaps bottom edge of intro text when it shouldn't
- [x] Fix sidescroll issue.
- [x] Fix search icon (not showing up)!
- [x] Make the zoomed-in state of the binoculars stay that way while content is open (target `.qqselected` within somepages.css, ~ line 786.
- [x] Fix trapezoid location.

**Design content display**
- [x] Temporarily fix fonts to not be Times Roman (may need to adjust which classes get the `font-family` assigned; currently it is on `m-textface` but may need to change it if I want a different size for the content description, etc).
- [x] Read bookmarked sites about custom tool tips.
- [x] Starting at fullscreen, decide the ideal content box layout, per binocular pair (use InDesign)
- [x] Repeat at all breakpoints as defined by qq-position-override.css's mediaqueries
- [x] Use these ideal layouts to define standard vs edge case layouts
- [x] ... and the breakpoints at which these content box styles should change
- Use CSS nth-child rule to target edge cases, first at 1225+ (e.g. (pseudocode) `qqpiece:nth-child(n*6) { ...`
- [x] Figure out if I can pass or calculate certain changeable parameters to CSS (content box height, content box location, footer location, screenwidth)
- [x] Plan sharkfin as an element: should there be just one JS-created sharkfin that gets passed around (current method), or HTML-created sharkfins with one per content box (would that work with existing scripts that navigate the DOM? could they be easily updated if needed?)?
- [x] Go through each class zone and determine math needed to position sharkfin + bordercover, and if CSS can be used
- [x] Write all CSS sharkfin-positioning code that I can per class zone
- [x] Write all remaining sharkfin-positioning JS needed per class zone
- [x] Edit original JS positions to _not_ use `padding` variable, if I can get them to "reset" to "position 0" instead
- [x] Code if-statement tree in JS that assigns class zones for <390.
- [x] Plan all zones' styles with math using available variables, by mapping out on paper.
- [x] Code all class styles that can be defined via CSS for <390.
- [x] Code all remaining zone styles via JS for <390.
- [x] Code zones for all arbitrarily-positioned binocs.
- [x] Get function to repeat if click outside of lens, knob, or trapezoid (just on container that causes zooming); likely should use a callback function for the if-statements within both scripts. _Update: Not possible for this to work with both functions, as I'd have to define both `var binoc` and `var content` based on the clicked element, which is by definition different for both parent functions that would be calling this one._
- [x] #167: Fix menu layering relative to QQ content boxes, via mediaqueries.
- [x] Fix and or log bugs.
- [x] Consider changing where content is stored, from image metadata to subpages.
- [x] If it is taking a long time to load, consider using original loading animation + method just for QQ page.
- [x] Add bugs from desktop to Github.
- [x] Clean up code (finesse zoom percentages), comments + push updates to server.
- [x]  #164: Yellow hover square on QQ content box's "x" gets cut off by border cover + push updates to server.
- [x] Set vertical spacing between description paragraphs.
- [x] Figure out how to make the main zone-assigning function within qq.js a callback function; it can be done!

Here is the practice version I built off my desktop (before I started building within Kirby localhost. Just including it here as a backup; all subsequent development should happen within Kirby localhost!
[mask-experiment.zip](https://github.com/liaprins/curiositycoloredglasses.com/files/2336580/mask-experiment.zip)

**Comment by liaprins** [comment]
For reference, the IBM binocular icons:
[ibm-design-icons-overview.zip](https://github.com/liaprins/curiositycoloredglasses.com/files/2336966/ibm-design-icons-overview.zip)

![overview_128](https://user-images.githubusercontent.com/17435353/44864798-699de600-ac35-11e8-9789-11af60eb3cb1.png)

**Comment by liaprins** [comment]
I DID IT 🤪
